from __future__ import annotations

import textwrap
from pathlib import Path


def _provider_config(provider: str, cloud: str, execution_mode: str) -> str:
    if provider == "snowflake":
        return textwrap.dedent(
            f"""
            provider:
              cloud: {cloud}
              account_env: SNOWFLAKE_ACCOUNT
              user_env: SNOWFLAKE_USER
              auth_type: externalbrowser
              warehouse: COMPUTE_WH
              role: SYSADMIN
              execution_mode: {execution_mode}
            """
        ).strip() + "\n"
    return textwrap.dedent(
        f"""
        provider:
          cloud: {cloud}
          connect_timeout_seconds: 10
          credential_mode: personal-access-token
          execution_mode: {execution_mode}
          auth_type: pat
          host_env: DATABRICKS_HOST
          token_env: DATABRICKS_TOKEN
          sql_warehouse_id_env: DATABRICKS_SQL_WAREHOUSE_ID
        """
    ).strip() + "\n"


def _environment_example(provider: str) -> str:
    if provider == "snowflake":
        return textwrap.dedent(
            """
            # Copy these values into your shell or CI secret store.
            # Browser SSO does not require a password in this file.
            SNOWFLAKE_ACCOUNT=your-organization-your-account
            SNOWFLAKE_USER=your-user
            """
        ).strip() + "\n"
    return textwrap.dedent(
        """
        # Copy these values into your shell or CI secret store.
        # Do not commit real tokens.
        DATABRICKS_HOST=https://your-workspace.cloud.databricks.com
        DATABRICKS_TOKEN=replace-with-your-personal-access-token
        DATABRICKS_SQL_WAREHOUSE_ID=replace-with-your-sql-warehouse-id
        """
    ).strip() + "\n"


def _workspace_config(provider: str, cloud: str) -> str:
    region = "us-west-2" if provider == "snowflake" else "eastus2"
    return (
        "workspace:\n"
        "  name: alpha-dev\n"
        f"  cloud: {cloud}\n"
        f"  region: {region}\n"
        "  catalogs:\n"
        "    - name: dm_alpha_marketing\n"
        "      use_default_storage: true\n"
        "      schemas:\n"
        "        - raw\n"
        "        - bronze\n"
        "        - silver\n"
        "        - gold\n"
    )


def _readme(name: str, provider: str) -> str:
    if provider == "snowflake":
        provider_testing = """
        ## Snowflake testing

        Set environment variables in the same terminal that runs DataMuru:

        ```powershell
        $env:SNOWFLAKE_ACCOUNT="your-organization-your-account"
        $env:SNOWFLAKE_USER="your-user"
        ```

        Browser SSO is the safe default. Keep `execution_mode: live-readonly`;
        Snowflake live apply and destroy are not available in this alpha.
        """
    else:
        provider_testing = """
        ## Databricks testing

        Set environment variables in the same terminal that runs DataMuru:

        ```powershell
        $env:DATABRICKS_HOST="https://your-workspace.cloud.databricks.com"
        $env:DATABRICKS_TOKEN="your-token"
        $env:DATABRICKS_SQL_WAREHOUSE_ID="your-warehouse-id"
        ```

        Start with `execution_mode: state-only` or `live-readonly`.
        Switch to `live-apply` only after reviewing a targeted plan.
        """
    common = textwrap.dedent(
        f"""
        # {name}

        This project was generated by `datamuru init`.

        ## Local validation

        ```powershell
        datamuru validate --config datamuru.yml
        datamuru plan --config datamuru.yml
        ```
        """
    ).strip()
    return f"{common}\n\n{textwrap.dedent(provider_testing).strip()}\n"


class ProjectScaffolder:
    def scaffold(
        self,
        output_dir: str | Path,
        *,
        name: str,
        provider: str = "databricks",
        cloud: str = "azure",
        edition: str = "open-source",
        execution_mode: str = "state-only",
    ) -> list[Path]:
        root = Path(output_dir)
        created: list[Path] = []
        for relative in [
            Path("environments"),
            Path("providers"),
            Path("workspaces"),
            Path("governance"),
        ]:
            target = root / relative
            target.mkdir(parents=True, exist_ok=True)
            created.append(target)

        content = {
            root / "datamuru.yml": textwrap.dedent(
                f"""
                project:
                  name: {name}
                  version: "0.1.0"
                  description: "Bootstrap DataMuru project"
                  edition: {edition}
                  provider: {provider}

                environments:
                  - name: dev
                    config: ./environments/dev.yml

                default_environment: dev

                features:
                  governance: true
                  data_mesh: false
                  ingestion: false
                  modeling: false
                  observability: false
                  compliance_reporting: false
                  multi_workspace: false
                  hosted_control_plane: false
                  identity_management: false

                state:
                  backend: local
                  path: ./.datamuru/state-dev.json

                provider:
                  name: {provider}
                  cloud: {cloud}
                  config: ./providers/{provider}.yml
                """
            ).strip() + "\n",
            root / "environments" / "dev.yml": "environment:\n  name: dev\n",
            root / "providers" / f"{provider}.yml": _provider_config(provider, cloud, execution_mode),
            root / "workspaces" / "alpha-dev.yml": _workspace_config(provider, cloud),
            root / "governance" / "taxonomy.yml": textwrap.dedent(
                """
                taxonomy:
                  name: bootstrap
                  version: "0.1"
                  categories:
                    - id: internal
                      label: Internal
                      description: "Internal data"
                      handling:
                        retention_years: 3
                        encryption: at_rest
                """
            ).strip() + "\n",
            root / "governance" / "rbac.yml": textwrap.dedent(
                """
                rbac:
                  roles:
                    - id: data_consumer
                      name: Data Consumer
                      permissions:
                        - resource_type: schema
                          resource_pattern: "*.gold"
                          privilege: SELECT
                  assignments:
                    - principal: sample-consumers
                      type: group
                      roles:
                        - data_consumer
                      domains:
                        - dm_alpha_marketing
                """
            ).strip() + "\n",
            root / "governance" / "masking.yml": textwrap.dedent(
                """
                masking:
                  builtins:
                    - id: partial_mask
                      description: Show last four characters for strings.
                      strategy: partial_mask
                """
            ).strip() + "\n",
            root / ".env.example": _environment_example(provider),
            root / "README.md": _readme(name, provider),
        }
        for path, value in content.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(value, encoding="utf-8")
            created.append(path)
        return created
